### ISSUE TITLE
[Suggestion] Use more forgiving selectors + observer

### ISSUE THREAD

**Issue by rauenzi** [TheLazySquid/DiscordUnicodeEmojis#1]
For your selectors like [this](https://github.com/TheLazySquid/DiscordUnicodeEmojis/blob/main/UnicodeEmojis.plugin.js#L54) it's more forgiving to use a regex selector like `[class*="textarea__"]` this makes the selectors more resilient to class rerolls from Discord's end. The performance impact is negligible from JS as opposed to CSS.

 I would also like to suggest thinking of a more robust observer than the one using [`requestAnimationFrame`](https://github.com/TheLazySquid/DiscordUnicodeEmojis/blob/main/UnicodeEmojis.plugin.js#L32). After testing, it's _okay_ but it can cause some little lags when typing fast into the editor in my experience.

**Comment by TheLazySquid** [comment]
Completely agree about the selector, I meant to fix it at some point but forgot.

The way that the text is observed is actually already through a MutationObserver- the requestAnimationFrame is there to prevent it from updating more than one emoji per frame. Without that, pasting in extremely large quantities of emojis will cause discord to hang until it's done swapping them all into unicode. I did add a check to make sure there's an emoji before looping through the text, which should hopefully prevent any lag.
